### ISSUE TITLE
Change availability (bool) of a job to "status" (enum). 

### ISSUE THREAD

**Issue by GhimpuLucianEduard** [ioana637/jobs-server#6]
Right now we are using a boolean to indicate whether or not a job is assigned.

I think it would be better to use an enum to describe the status of a job:

``public enum JobStatus {
      AVAILABLE, ASSIGNED, COMPLETED }``

This way a client could mark a job as completed.

**Comment by ioana637** [comment]
Yes, it's ok to use enum.

**Comment by Sinars** [comment]
change made
